export const BETRAYAL_VISUAL_TRANSITION_DURATION_MS = 560;
export const BETRAYAL_DISCOVERY_ITEM_AUTO_ADVANCE_DELAY_MS = 3000;

// 本地 AI 的可见动作需要覆盖目标查找和过渡播放，才不会在移动/收牌动画中抢先提交下一步。
export const BETRAYAL_AI_MINIMUM_VISIBLE_STEP_DELAY_MS = 900;
